# If True then the player can Right Click + Sneak a boat to open the inventory
AllowRightClickInteract: true

# Inventory size that applies to all boats by default
# Inventory size must be multiple of 9 and less than 256
# Use 0 if the boat doesn't have inventory
DefaultBoatInventory: 0

# Allowed boat types: OAK, REDWOOD, BIRCH, JUNGLE, ACACIA, DARK_OAK
Boats:
  OAK:
    Inventory: 54
  BIRCH:
    Inventory: 108